name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 3.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  archive: ^3.3.0
  quiver: ^3.1.0
  xml: ^6.0.1
  image: ^3.2.0

dev_dependencies:
  test: any
  path: any
